version: 2

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"

  # Maintain dependencies for Python
  - package-ecosystem: "pip" 
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
