blank_issues_enabled: false
contact_links:
  - name: Discussions
  - url: https://github.com/cwellm/Simple-Filter/discussions/
    about: Discuss about our software!
  - name: Christoph Wellm
    url: https://github.com/cwellm/Simple-Filter
    about: Please conduct the README for more information about contacts.