# syntax=docker/dockerfile:1.6.0

# ------------ first stage: build cmake ------------

FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 as windows-cmake

ARG cmake_version=3.27.2

#https://github.com/Kitware/CMake/releases/download/v3.27.2/cmake-3.27.2-windows-x86_64.msi