name: Build

on:
  push:
    branches:
      - main
      - I1_set-up-repository
  pull_request:

jobs:
  on: ubuntu-22.04
  env:
    Dockerfile: Dockerfile.Linux
  build:
    - name: Execute Build
      run: docker compose up --build
    - name: Clean up
      run: docker compose down
