name: Build
run-name: Build

on:
  push:
    branches:
      - main
      - I1_set-up-repository
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      Dockerfile: CI/Dockerfile.Linux
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Execute Build
        run: docker compose up --build
      - name: Clean up
        run: docker compose down
